"""YOLOv8-pose 训练数据导出器

将生成图像 + 关键点标注导出为 YOLO 格式：
    datasets/{event_type}/
        images/
            000001.jpg
            000002.jpg
            ...
        labels/
            000001.txt
            000002.txt
            ...

YOLO 关键点格式 (每行):
    class_id cx cy w h kp1x kp1y kp1v ... kp17x kp17y kp17v
    - 坐标均为归一化值 (0~1)
    - kp*v: 0=不可见, 1=遮挡, 2=可见
"""

import json
import logging
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional
from uuid import uuid4

from PIL import Image

from .config import IMAGES_DIR, LABELS_DIR, DATASETS_DIR

logger = logging.getLogger(__name__)


def _format_yolo_line(
    category_id: int,
    bbox: List[float],
    keypoints: List[List[float]],
) -> str:
    """格式化一行 YOLO 关键点标注

    Args:
        category_id: 类别 ID (0-based)
        bbox: [cx, cy, w, h] 归一化坐标
        keypoints: 17 个 [x, y]，归一化坐标

    Returns:
        YOLO 格式标注行字符串
    """
    parts = [str(category_id)]
    # bbox: cx cy w h
    parts.extend(f"{v:.6f}" for v in bbox)
    # keypoints: 17 * (x, y, visibility=2)
    for kp in keypoints:
        parts.extend([
            f"{kp[0]:.6f}",
            f"{kp[1]:.6f}",
            "2.0" if (kp[0] != 0 or kp[1] != 0) else "0.0",
        ])
    return " ".join(parts)


def export_single(
    result: Dict[str, Any],
    base_name: str,
    image_dir: Path,
    labels_dir: Path,
    category_id: int = 0,
) -> Dict[str, str]:
    """导出单张生成结果的图像与标签

    Args:
        result: generator.generate_single 的返回值
        base_name: 文件名（不含扩展名）
        image_dir: 图像输出目录
        labels_dir: 标签输出目录
        category_id: YOLO 类别 ID

    Returns:
        dict: {image_path, label_path}
    """
    image_path = image_dir / f"{base_name}.jpg"
    label_path = labels_dir / f"{base_name}.txt"

    # 保存图像
    result["image"].save(image_path, "JPEG", quality=95)

    # 保存 YOLO 关键点标签
    yolo_line = _format_yolo_line(category_id, result["bbox"], result["keypoints"])
    label_path.write_text(yolo_line, encoding="utf-8")

    return {"image_path": str(image_path), "label_path": str(label_path)}


def export_dataset(
    results: List[Dict[str, Any]],
    dataset_name: str,
    category_id: int = 0,
) -> Path:
    """批量导出为 YOLO 数据集

    Args:
        results: 生成结果列表
        dataset_name: 数据集名称（用于子目录）
        category_id: YOLO 类别 ID

    Returns:
        Path: 数据集根目录
    """
    dataset_dir = DATASETS_DIR / dataset_name
    img_dir = dataset_dir / "images"
    lbl_dir = dataset_dir / "labels"

    # 清理旧数据
    if dataset_dir.exists():
        shutil.rmtree(dataset_dir)
    img_dir.mkdir(parents=True, exist_ok=True)
    lbl_dir.mkdir(parents=True, exist_ok=True)

    manifests = []

    for i, result in enumerate(results):
        base_name = f"{i:06d}"
        paths = export_single(result, base_name, img_dir, lbl_dir, category_id)

        manifests.append({
            "id": i,
            "filename": f"{base_name}.jpg",
            "event_type": result["event_type"],
            "label": result["label"],
            "seed": result["seed"],
            "night_mode": result["night_mode"],
            "generation_time_ms": result["generation_time_ms"],
        })

    # 保存 manifest
    manifest = {
        "dataset_name": dataset_name,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "total_images": len(results),
        "image_size": 640,
        "format": "yolo-pose",
        "category_id": category_id,
        "entries": manifests,
    }
    (dataset_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    # 生成 data.yaml
    yaml_content = f"""# YOLOv8-pose dataset config (auto-generated by diffusion-service)
path: {dataset_dir}
train: images
val: images  # 扩散生成数据暂不分 train/val，可手动划分

nc: 1
names:
  {category_id}: {dataset_name}

kpt_shape: [17, 3]
"""
    (dataset_dir / "data.yaml").write_text(yaml_content, encoding="utf-8")

    logger.info(f"Dataset exported: {dataset_dir} ({len(results)} images)")
    return dataset_dir


def export_multi_event_dataset(
    results_by_event: Dict[str, List[Dict[str, Any]]],
    dataset_name: str = "smart-ward-augmented",
) -> Path:
    """多事件混合数据集导出

    Args:
        results_by_event: {event_type: [results]}
        dataset_name: 数据集名称

    Returns:
        数据集根目录
    """
    from config.pose_templates import EVENT_CATEGORY_IDS

    dataset_dir = DATASETS_DIR / dataset_name
    img_dir = dataset_dir / "images"
    lbl_dir = dataset_dir / "labels"

    if dataset_dir.exists():
        shutil.rmtree(dataset_dir)
    img_dir.mkdir(parents=True, exist_ok=True)
    lbl_dir.mkdir(parents=True, exist_ok=True)

    idx = 0
    manifests = []
    category_names = {}

    for event_type, results in results_by_event.items():
        cat_id = EVENT_CATEGORY_IDS.get(event_type, 0)
        category_names[cat_id] = event_type

        for result in results:
            base_name = f"{idx:06d}"
            export_single(result, base_name, img_dir, lbl_dir, cat_id)

            manifests.append({
                "id": idx,
                "filename": f"{base_name}.jpg",
                "event_type": event_type,
                "category_id": cat_id,
                "label": result["label"],
                "seed": result["seed"],
                "night_mode": result["night_mode"],
            })
            idx += 1

    # 生成带有所有类别配置的 data.yaml
    names_str = "\n".join(f"  {cid}: {cname}" for cid, cname in sorted(category_names.items()))
    yaml_content = f"""# YOLOv8-pose multi-class dataset config
path: {dataset_dir}
train: images
val: images

nc: {len(category_names)}
names:
{names_str}

kpt_shape: [17, 3]
"""
    (dataset_dir / "data.yaml").write_text(yaml_content, encoding="utf-8")

    manifest = {
        "dataset_name": dataset_name,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "total_images": idx,
        "categories": category_names,
        "image_size": 640,
        "format": "yolo-pose",
        "entries": manifests,
    }
    (dataset_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    logger.info(f"Multi-event dataset exported: {dataset_dir} ({idx} images)")
    return dataset_dir
